<div class="footer-about"> 
    <img src="<?php echo $this->getViewFileUrl('images/logow.png'); ?>" width="150px" class="footer-logo" />
    <p class="about-company">Dystrybucją sprzętu sportowego zajmujemy się już od 2006 roku. Naszą misją jest wsparcie w profesjonalnym wyborze sprzętu hokejowego.</p>
    <div class="footer-icons">
        <a href="#" class="footer-icon">
            <i class="fa fa-facebook" aria-hidden="true"></i>
        </a>
        <a href="#" class="footer-icon">
            <i class="fa fa-twitter" aria-hidden="true"></i>
        </a>
        <a href="#" class="footer-icon">
            <i class="fa fa-google-plus" aria-hidden="true"></i>
        </a>
        <a href="#" class="footer-icon">
            <i class="fa fa-amazon" aria-hidden="true"></i>
        </a>
        <a href="#" class="footer-icon">
            <i class="fa fa-vimeo" aria-hidden="true"></i>
        </a>
        <a href="#" class="footer-icon">
            <i class="fa fa-pinterest-p" aria-hidden="true"></i>
        </a>
    </div>
</div>