<div class="contact-container">
    <h3 class="footer-title">Kontakt</h3>
    <div class="contact-box">
        <p class="contact-title contact-title--address">Adres</p>
        <p class="contact-value">Warszawa, Mińska 51B</p>
    </div>
    <div class="contact-box">
        <p class="contact-title contact-title--phone">Telefon</p>
        <p class="contact-value">(+45) 792 344 076</p>
    </div>
    <div class="contact-box">
        <p class="contact-title contact-title--mail">Email</p>
        <p class="contact-value">support@purehockey.com</p>
    </div>
</div>